export const CART_ACTION_TYPES = {
    ADD_CART_ITEM: 'ADD_CART_ITEM',
    DELETE_CART_ITEM: 'DELETE_CART_ITEM',
    INCREMENT_CART_ITEM: 'INCREMENT_CART_ITEM',
    DECREMENT_CART_ITEM: 'DECREMENT_CART_ITEM',
}